#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------

- name: Create {{ dockerfile_prefix }} Docker file
  template:
    src: "{{ dockerfile_prefix }}_Dockerfile"
    dest: "/data/registry/repositories/{{ base_os_image }}_{{ layer_suffix }}/Dockerfile"
    owner: root
    mode: 0644

- name: Build the image {{ layer_suffix }}
  command: "docker build -q -t {{ inventory_hostname }}:{{ docker_registry_port }}/{{ base_os_image }}_{{ layer_suffix }} ."
  args:
    chdir: "/data/registry/repositories/{{ base_os_image }}_{{ layer_suffix }}"
  register: command_result
  failed_when: "'sha256:' not in command_result.stdout"

- name: Push the Image {{ layer_suffix }} in the repository
  command: "docker push {{ inventory_hostname }}:{{ docker_registry_port }}/{{ base_os_image }}_{{ layer_suffix }}"
