ibm_container_install_dir: opt/ibm
lxc_device: /home/docker_device
storlet_source_dir: ~/swift-storlets
python_dist_packages_dir: usr/local/lib/python2.7/dist-packages
storlet_gateway_conf_file: /etc/swift/storlet_docker_gateway.conf

#----------------------------------------------------------------
# storlet_management / swift_storlet_management

# The below keystone vars MUST be synchronized with the swift_install variables.
keystone_endpoint_host: <Set Me!>
keystone_admin_url: "http://{{ keystone_endpoint_host }}:35357/v2.0"
keystone_public_url: "http://{{ keystone_endpoint_host }}:5000/v2.0"
keystone_admin_token: ADMIN
keystone_admin_password: passw0rd

swift_endpoint_host: <Set Me!>
swift_public_url: "http://{{ swift_endpoint_host }}:80/v1"

storlet_management_account: storlet_management
storlet_management_admin_username: storlet_manager
storlet_manager_admin_password: storlet_manager
storlet_management_swift_topology_container: swift_cluster
storlet_management_swift_topology_object : swift_cluster_nodes

storlet_management_ansible_dir: /opt/ibm/ansible/playbook
storlet_management_install_dir: /opt/ibm

# The below attribute can take true / false
storlets_enabled_attribute_name: storlet-enabled
#----------------------------------------------------------------

#----------------------------------------------------------------
# Storlets default tenant
storlets_default_tenant_name: service
storlets_default_tenant_user_name: swift
storlets_default_tenant_user_password: passw0rd

#----------------------------------------------------------------
#----------------------------------------------------------------
# docker_repository / docker_registry 
docker_registry_random_string: ABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJ1234
docker_registry_port: 5001
#----------------------------------------------------------------

#----------------------------------------------------------------
# docker_base_storlet_images / docekr_base_images 
base_image_maintainer: root
base_os_image: ubuntu_14.04
storlets_image_name_suffix: ubuntu_14.04_jre7_storlets
swift_user_id: 1003
swift_group_id: 1003
#----------------------------------------------------------------

#----------------------------------------------------------------
# middleware and gateway config file constants
storlet_middleware: storlet_handler
storlet_container: storlet
storlet_dependency: dependency
storlet_log: storletlog
storlet_images: docker_images
storlet_timeout: 40
storlet_gateway_module: storlet_gateway.storlet_docker_gateway:StorletGatewayDocker
restart_linux_container_timeout: 3
#----------------------------------------------------------------
