# Copyright (c) 2016 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: create installation directory
  file: path={{ engine_install_dir }} state=directory recurse=yes

- name: Copy Swift middleware conf template
  template:
    src: ../../common_templates/swift_middleware_conf
    dest: "{{ engine_install_dir  }}"
    owner: "{{ swift_run_time_user }}"
    group: "{{ swift_run_time_group }}"
    mode: 0644

- name: copy install script
  copy: src="{{ item }}" dest={{ engine_install_dir  }}
  with_items:
   - ../../common_files/swift_config.py

- name: Copy gateway conf template
  template:
    src: ../../common_templates/storlet-docker-gateway.conf-sample
    dest: "{{ storlet_gateway_conf_file }}"
    owner: "{{ swift_run_time_user }}"
    group: "{{ swift_run_time_group }}"
    mode: 0644

- name: configure swift
  shell: chdir={{ engine_install_dir }}
         python swift_config.py install swift_middleware_conf "{{ swift_run_time_user }}"

- name: restart swift
  shell: swift-init --run-dir="{{swift_run_time_dir}}" all restart
  ignore_errors: yes
